#pragma once




#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define DOT_AT "." /*" In file " __FILE__ ":" TOSTRING(__LINE__)*/


#define WHICH_IS ", which is "
#define WHICH_ARE ", which are "
#define BUT_IS ", but is "
#define FLOAT "float"
#define DOUBLE "double"
#define VEC2 "glm::tvec2"
#define VEC3 "glm::tvec3"
#define VEC4 "glm::tvec4"




#define KERNEL_MUST_SCALAR "Kernel must be of a floating scalar cell type"
#define KERNEL_MUST_VEC2 "Kernel must be of cell type glm::tvec2"
#define KERNEL_MUST_VEC3 "Kernel must be of cell type glm::tvec3"
#define KERNEL_MUST_VEC4 "Kernel must be of cell type glm::tvec4"

#define SCALAR_KERNEL_CELLTYPE_MATCH_VEC2 KERNEL_MUST_SCALAR BUT_IS VEC2 DOT_AT
#define SCALAR_KERNEL_CELLTYPE_MATCH_VEC3 KERNEL_MUST_SCALAR BUT_IS VEC3 DOT_AT
#define SCALAR_KERNEL_CELLTYPE_MATCH_VEC4 KERNEL_MUST_SCALAR BUT_IS VEC4 DOT_AT

#define VEC2_KERNEL_CELLTYPE_MATCH_FLOAT KERNEL_MUST_VEC2 BUT_IS FLOAT DOT_AT
#define VEC2_KERNEL_CELLTYPE_MATCH_DOUBLE KERNEL_MUST_VEC2 BUT_IS DOUBLE DOT_AT

#define VEC2_KERNEL_CELLTYPE_MATCH_VEC3 KERNEL_MUST_VEC2 BUT_IS VEC3 DOT_AT
#define VEC2_KERNEL_CELLTYPE_MATCH_VEC4 KERNEL_MUST_VEC2 BUT_IS VEC4 DOT_AT

#define VEC3_KERNEL_CELLTYPE_MATCH_FLOAT KERNEL_MUST_VEC3 BUT_IS FLOAT DOT_AT
#define VEC3_KERNEL_CELLTYPE_MATCH_DOUBLE KERNEL_MUST_VEC3 BUT_IS DOUBLE DOT_AT

#define VEC3_KERNEL_CELLTYPE_MATCH_VEC2 KERNEL_MUST_VEC3 BUT_IS VEC2 DOT_AT
#define VEC3_KERNEL_CELLTYPE_MATCH_VEC4 KERNEL_MUST_VEC3 BUT_IS VEC4 DOT_AT

#define VEC4_KERNEL_CELLTYPE_MATCH_FLOAT KERNEL_MUST_VEC4 BUT_IS FLOAT DOT_AT
#define VEC4_KERNEL_CELLTYPE_MATCH_DOUBLE KERNEL_MUST_VEC4 BUT_IS DOUBLE DOT_AT

#define VEC4_KERNEL_CELLTYPE_MATCH_VEC2 KERNEL_MUST_VEC4 BUT_IS VEC2 DOT_AT
#define VEC4_KERNEL_CELLTYPE_MATCH_VEC3 KERNEL_MUST_VEC4 BUT_IS VEC3 DOT_AT


#define VEC2_OR_VEC3_KERNEL_CELLTYPE_MATCH_FLOAT KERNEL_MUST_VEC2 " or " VEC3 BUT_IS FLOAT DOT_AT
#define VEC2_OR_VEC3_KERNEL_CELLTYPE_MATCH_DOUBLE KERNEL_MUST_VEC2 " or " BUT_IS DOUBLE DOT_AT




#define PARAMS_MUST_EQUAL_KERNELTYPE "Types of kernel parameters must be equal and match kernel "
#define PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE PARAMS_MUST_EQUAL_KERNELTYPE "component type"
#define PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE PARAMS_MUST_EQUAL_KERNELTYPE "component- or cell type"

#define PARAMS_EQUAL_MATCH_FLOAT PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE WHICH_IS FLOAT DOT_AT
#define PARAMS_EQUAL_MATCH_DOUBLE PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE WHICH_IS DOUBLE DOT_AT

#define PARAMS_EQUAL_MATCH_FLOAT_OR_VEC2 PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE FLOAT " and " VEC2 DOT_AT
#define PARAMS_EQUAL_MATCH_FLOAT_OR_VEC3 PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE FLOAT " and " VEC3 DOT_AT
#define PARAMS_EQUAL_MATCH_FLOAT_OR_VEC4 PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE FLOAT " and " VEC4 DOT_AT
#define PARAMS_EQUAL_MATCH_DOUBLE_OR_VEC2 PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE DOUBLE " and " VEC2 DOT_AT
#define PARAMS_EQUAL_MATCH_DOUBLE_OR_VEC3 PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE DOUBLE " and " VEC3 DOT_AT
#define PARAMS_EQUAL_MATCH_DOUBLE_OR_VEC4 PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE DOUBLE " and " VEC4 DOT_AT




#define PARAMS_MUST_KERNEL_COMPONENTTYPE "Component type of kernel parameter(s) must match kernel component type"
#define PARAMS_MATCH_FLOAT PARAMS_MUST_KERNEL_COMPONENTTYPE WHICH_IS FLOAT DOT_AT
#define PARAMS_MATCH_DOUBLE PARAMS_MUST_KERNEL_COMPONENTTYPE WHICH_IS DOUBLE DOT_AT

#define PARAMS_MUST_KERNEL_CELLTYPE "Cell type of kernel parameter(s) must match kernel cell type"
#define PARAMS_MATCH_VEC2 PARAMS_MUST_KERNEL_CELLTYPE WHICH_IS VEC2 DOT_AT
#define PARAMS_MATCH_VEC3 PARAMS_MUST_KERNEL_CELLTYPE WHICH_IS VEC3 DOT_AT
#define PARAMS_MATCH_VEC4 PARAMS_MUST_KERNEL_CELLTYPE WHICH_IS VEC4 DOT_AT



#define PARAM_MUST_KERNEL_FLOAT "Component type of kernel parameter must match kernel component type" WHICH_IS FLOAT
#define PARAM_MUST_KERNEL_DOUBLE "Component type of kernel parameter must match kernel component type" WHICH_IS DOUBLE

#define FLOAT_PARAM_MATCH_VEC2 PARAM_MUST_KERNEL_FLOAT BUT_IS VEC2 DOT_AT
#define FLOAT_PARAM_MATCH_VEC3 PARAM_MUST_KERNEL_FLOAT BUT_IS VEC3 DOT_AT
#define FLOAT_PARAM_MATCH_VEC4 PARAM_MUST_KERNEL_FLOAT BUT_IS VEC4 DOT_AT

#define DOUBLE_PARAM_MATCH_VEC2 PARAM_MUST_KERNEL_DOUBLE BUT_IS VEC2 DOT_AT
#define DOUBLE_PARAM_MATCH_VEC3 PARAM_MUST_KERNEL_DOUBLE BUT_IS VEC3 DOT_AT
#define DOUBLE_PARAM_MATCH_VEC4 PARAM_MUST_KERNEL_DOUBLE BUT_IS VEC4 DOT_AT




#define NOT_VEC2_KERNEL_CELLTYPE "Kernel of type glm::tvec2 is not supported!"
#define NOT_VEC3_KERNEL_CELLTYPE "Kernel of type glm::tvec3 is not supported!"
#define NOT_VEC4_KERNEL_CELLTYPE "Kernel of type glm::tvec4 is not supported!"
