#pragma once



#define IDF "<Kernel Template Error>: "


#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define DOT_AT "." /*" In file " __FILE__ ":" TOSTRING(__LINE__)*/


#define WHICH_IS ", which is "
#define WHICH_ARE ", which are "
#define BUT_IS ", but it is "
#define FLOAT "float"
#define DOUBLE "double"
#define VEC2 "glm::tvec2"
#define VEC3 "glm::tvec3"
#define VEC4 "glm::tvec4"




#define KERNEL_MUST_SCALAR "Kernel must be of a floating scalar cell type"
#define KERNEL_MUST_VEC2 "Kernel must be of cell type glm::tvec2"
#define KERNEL_MUST_VEC3 "Kernel must be of cell type glm::tvec3"
#define KERNEL_MUST_VEC4 "Kernel must be of cell type glm::tvec4"

#define SCALAR_KERNEL_CELLTYPE_MATCH_VEC2 IDF KERNEL_MUST_SCALAR BUT_IS VEC2 DOT_AT
#define SCALAR_KERNEL_CELLTYPE_MATCH_VEC3 IDF KERNEL_MUST_SCALAR BUT_IS VEC3 DOT_AT
#define SCALAR_KERNEL_CELLTYPE_MATCH_VEC4 IDF KERNEL_MUST_SCALAR BUT_IS VEC4 DOT_AT

#define VEC2_KERNEL_CELLTYPE_MATCH_FLOAT IDF KERNEL_MUST_VEC2 BUT_IS FLOAT DOT_AT
#define VEC2_KERNEL_CELLTYPE_MATCH_DOUBLE IDF KERNEL_MUST_VEC2 BUT_IS DOUBLE DOT_AT

#define VEC2_KERNEL_CELLTYPE_MATCH_VEC3 IDF KERNEL_MUST_VEC2 BUT_IS VEC3 DOT_AT
#define VEC2_KERNEL_CELLTYPE_MATCH_VEC4 IDF KERNEL_MUST_VEC2 BUT_IS VEC4 DOT_AT

#define VEC3_KERNEL_CELLTYPE_MATCH_FLOAT IDF KERNEL_MUST_VEC3 BUT_IS FLOAT DOT_AT
#define VEC3_KERNEL_CELLTYPE_MATCH_DOUBLE IDF KERNEL_MUST_VEC3 BUT_IS DOUBLE DOT_AT

#define VEC3_KERNEL_CELLTYPE_MATCH_VEC2 IDF KERNEL_MUST_VEC3 BUT_IS VEC2 DOT_AT
#define VEC3_KERNEL_CELLTYPE_MATCH_VEC4 IDF KERNEL_MUST_VEC3 BUT_IS VEC4 DOT_AT

#define VEC4_KERNEL_CELLTYPE_MATCH_FLOAT IDF KERNEL_MUST_VEC4 BUT_IS FLOAT DOT_AT
#define VEC4_KERNEL_CELLTYPE_MATCH_DOUBLE IDF KERNEL_MUST_VEC4 BUT_IS DOUBLE DOT_AT

#define VEC4_KERNEL_CELLTYPE_MATCH_VEC2 IDF KERNEL_MUST_VEC4 BUT_IS VEC2 DOT_AT
#define VEC4_KERNEL_CELLTYPE_MATCH_VEC3 IDF KERNEL_MUST_VEC4 BUT_IS VEC3 DOT_AT


#define VEC2_OR_VEC3_KERNEL_CELLTYPE_MATCH_FLOAT IDF KERNEL_MUST_VEC2 " or " VEC3 BUT_IS FLOAT DOT_AT
#define VEC2_OR_VEC3_KERNEL_CELLTYPE_MATCH_DOUBLE IDF KERNEL_MUST_VEC2 " or " BUT_IS DOUBLE DOT_AT




#define PARAMS_MUST_EQUAL_KERNELTYPE "Types of kernel parameters must be equal and match kernel "
#define PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE PARAMS_MUST_EQUAL_KERNELTYPE "component type"
#define PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE PARAMS_MUST_EQUAL_KERNELTYPE "component- or cell type"

#define PARAMS_EQUAL_MATCH_FLOAT IDF PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE WHICH_IS FLOAT DOT_AT
#define PARAMS_EQUAL_MATCH_DOUBLE IDF PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE WHICH_IS DOUBLE DOT_AT

#define PARAMS_EQUAL_MATCH_FLOAT_OR_VEC2 IDF PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE FLOAT " and " VEC2 DOT_AT
#define PARAMS_EQUAL_MATCH_FLOAT_OR_VEC3 IDF PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE FLOAT " and " VEC3 DOT_AT
#define PARAMS_EQUAL_MATCH_FLOAT_OR_VEC4 IDF PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE FLOAT " and " VEC4 DOT_AT
#define PARAMS_EQUAL_MATCH_DOUBLE_OR_VEC2 IDF PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE DOUBLE " and " VEC2 DOT_AT
#define PARAMS_EQUAL_MATCH_DOUBLE_OR_VEC3 IDF PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE DOUBLE " and " VEC3 DOT_AT
#define PARAMS_EQUAL_MATCH_DOUBLE_OR_VEC4 IDF PARAMS_MUST_EQUAL_KERNEL_COMPONENTTYPE_OR_CELLTYPE WHICH_ARE DOUBLE " and " VEC4 DOT_AT




#define ARGUMENTS_MUST_EQUAL IDF "Types of arguments must be equal" DOT_AT




#define PARAMS_MUST_KERNEL_COMPONENTTYPE "Type(s) of kernel parameter(s) must match kernel component type"
#define PARAMS_MATCH_FLOAT IDF PARAMS_MUST_KERNEL_COMPONENTTYPE WHICH_IS FLOAT DOT_AT
#define PARAMS_MATCH_DOUBLE IDF PARAMS_MUST_KERNEL_COMPONENTTYPE WHICH_IS DOUBLE DOT_AT

#define PARAMS_MUST_KERNEL_CELLTYPE "Type(s) of kernel parameter(s) must match kernel cell type"
#define PARAMS_MATCH_VEC2 IDF PARAMS_MUST_KERNEL_CELLTYPE WHICH_IS VEC2 DOT_AT
#define PARAMS_MATCH_VEC3 IDF PARAMS_MUST_KERNEL_CELLTYPE WHICH_IS VEC3 DOT_AT
#define PARAMS_MATCH_VEC4 IDF PARAMS_MUST_KERNEL_CELLTYPE WHICH_IS VEC4 DOT_AT




#define PARAM_MUST_KERNEL_FLOAT "Type of kernel parameter must match kernel component type (which is " FLOAT ")"
#define PARAM_MUST_KERNEL_DOUBLE "Type of kernel parameter must match kernel component type (which is " DOUBLE ")"

#define FLOAT_PARAM_MATCH_VEC2 IDF PARAM_MUST_KERNEL_FLOAT BUT_IS VEC2 DOT_AT
#define FLOAT_PARAM_MATCH_VEC3 IDF PARAM_MUST_KERNEL_FLOAT BUT_IS VEC3 DOT_AT
#define FLOAT_PARAM_MATCH_VEC4 IDF PARAM_MUST_KERNEL_FLOAT BUT_IS VEC4 DOT_AT

#define DOUBLE_PARAM_MATCH_VEC2 IDF PARAM_MUST_KERNEL_DOUBLE BUT_IS VEC2 DOT_AT
#define DOUBLE_PARAM_MATCH_VEC3 IDF PARAM_MUST_KERNEL_DOUBLE BUT_IS VEC3 DOT_AT
#define DOUBLE_PARAM_MATCH_VEC4 IDF PARAM_MUST_KERNEL_DOUBLE BUT_IS VEC4 DOT_AT




#define PARAM_MUST_KERNEL_VEC2 "Type of kernel parameter must match kernel cell type (which is " VEC2 ")"
#define PARAM_MUST_KERNEL_VEC3 "Type of kernel parameter must match kernel cell type (which is " VEC3 ")"
#define PARAM_MUST_KERNEL_VEC4 "Type of kernel parameter must match kernel cell type (which is " VEC4 ")"

#define VEC2_PARAM_MATCH_FLOAT IDF PARAM_MUST_KERNEL_VEC2 BUT_IS FLOAT DOT_AT
#define VEC2_PARAM_MATCH_DOUBLE IDF PARAM_MUST_KERNEL_VEC2 BUT_IS DOUBLE DOT_AT

#define VEC3_PARAM_MATCH_FLOAT IDF PARAM_MUST_KERNEL_VEC3 BUT_IS FLOAT DOT_AT
#define VEC3_PARAM_MATCH_DOUBLE IDF PARAM_MUST_KERNEL_VEC3 BUT_IS DOUBLE DOT_AT

#define VEC4_PARAM_MATCH_FLOAT IDF PARAM_MUST_KERNEL_VEC4 BUT_IS FLOAT DOT_AT
#define VEC4_PARAM_MATCH_DOUBLE IDF PARAM_MUST_KERNEL_VEC4 BUT_IS DOUBLE DOT_AT




#define NOT_VEC2_KERNEL_CELLTYPE IDF "Kernel of type glm::tvec2 is not supported!"
#define NOT_VEC3_KERNEL_CELLTYPE IDF "Kernel of type glm::tvec3 is not supported!"
#define NOT_VEC4_KERNEL_CELLTYPE IDF "Kernel of type glm::tvec4 is not supported!"
