#pragma once

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define AT /*" In file " __FILE__ ":" TOSTRING(__LINE__)*/


#define WHICH_IS ", which is "
#define BUT_IS ", but is "
#define FLOAT "float."
#define DOUBLE "double."
#define VEC2 "glm::tvec2."
#define VEC3 "glm::tvec3."
#define VEC4 "glm::tvec4."


#define KERNEL_FLOATING "Kernel must be of a floating type (float or double)!"

#define PARAM_MUST_KERNEL "Type of kernel parameter(s) must match kernel type"
#define PARAM_MATCH_FLOAT PARAM_MUST_KERNEL WHICH_IS FLOAT AT
#define PARAM_MATCH_DOUBLE PARAM_MUST_KERNEL WHICH_IS DOUBLE AT

#define PARAM_MUST_CELL "Celltype of kernel parameter(s) must match kernel celltype"
#define PARAM_MATCH_VEC2 PARAM_MUST_CELL WHICH_IS VEC2 AT
#define PARAM_MATCH_VEC3 PARAM_MUST_CELL WHICH_IS VEC3 AT
#define PARAM_MATCH_VEC4 PARAM_MUST_CELL WHICH_IS VEC4 AT


#define KERNEL_MUST_SCALAR "Kernel must be of a scalar (floating: float or double) type"
#define KERNEL_MUST_VEC2 "Kernel must be of type glm::tvec2"
#define KERNEL_MUST_VEC3 "Kernel must be of type glm::tvec3"
#define KERNEL_MUST_VEC4 "Kernel must be of type glm::tvec4"

#define VEC2_KERNEL_CELLTYPE_MATCH_FLOAT KERNEL_MUST_VEC2 BUT_IS FLOAT AT
#define VEC2_KERNEL_CELLTYPE_MATCH_DOUBLE KERNEL_MUST_VEC2 BUT_IS DOUBLE AT

#define VEC3_KERNEL_CELLTYPE_MATCH_FLOAT KERNEL_MUST_VEC3 BUT_IS FLOAT AT
#define VEC3_KERNEL_CELLTYPE_MATCH_DOUBLE KERNEL_MUST_VEC3 BUT_IS DOUBLE AT

#define VEC4_KERNEL_CELLTYPE_MATCH_FLOAT KERNEL_MUST_VEC4 BUT_IS FLOAT AT
#define VEC4_KERNEL_CELLTYPE_MATCH_DOUBLE KERNEL_MUST_VEC4 BUT_IS DOUBLE AT


#define VEC2_KERNEL_CELLTYPE_MATCH_VEC3 KERNEL_MUST_VEC2 BUT_IS VEC3 AT
#define VEC2_KERNEL_CELLTYPE_MATCH_VEC4 KERNEL_MUST_VEC2 BUT_IS VEC4 AT

#define VEC3_KERNEL_CELLTYPE_MATCH_VEC2 KERNEL_MUST_VEC3 BUT_IS VEC2 AT
#define VEC3_KERNEL_CELLTYPE_MATCH_VEC4 KERNEL_MUST_VEC3 BUT_IS VEC4 AT

#define VEC4_KERNEL_CELLTYPE_MATCH_VEC2 KERNEL_MUST_VEC4 BUT_IS VEC2 AT
#define VEC4_KERNEL_CELLTYPE_MATCH_VEC3 KERNEL_MUST_VEC4 BUT_IS VEC3 AT

#define SCALAR_KERNEL_CELLTYPE_MATCH_VEC2 KERNEL_MUST_SCALAR BUT_IS VEC2 AT
#define SCALAR_KERNEL_CELLTYPE_MATCH_VEC3 KERNEL_MUST_SCALAR BUT_IS VEC3 AT
#define SCALAR_KERNEL_CELLTYPE_MATCH_VEC4 KERNEL_MUST_SCALAR BUT_IS VEC4 AT


#define PARAM_MUST_FLOAT "Parameter must be of type float"
#define PARAM_MUST_DOUBLE "Parameter must be of type float"

#define FLOAT_PARAM_TYPE_MATCH_VEC2 PARAM_MUST_FLOAT BUT_IS VEC2 AT
#define FLOAT_PARAM_TYPE_MATCH_VEC3 PARAM_MUST_FLOAT BUT_IS VEC3 AT
#define FLOAT_PARAM_TYPE_MATCH_VEC4 PARAM_MUST_FLOAT BUT_IS VEC4 AT

#define DOUBLE_PARAM_TYPE_MATCH_VEC2 PARAM_MUST_DOUBLE BUT_IS VEC2 AT
#define DOUBLE_PARAM_TYPE_MATCH_VEC3 PARAM_MUST_DOUBLE BUT_IS VEC3 AT
#define DOUBLE_PARAM_TYPE_MATCH_VEC4 PARAM_MUST_DOUBLE BUT_IS VEC4 AT
